name: Main

on:
  push:
  pull_request:

env:
  GO_VERSION: '1.21'
  GOLANGCI_LINT_VERSION: v1.54.2
  TINYGO_VERSION: '0.30.0'
  # YAEGI_VERSION: v0.15.1

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    steps:
      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

